### ISSUE TITLE
I can has MIT license?

### ISSUE THREAD

**Issue by Slids** [phoe/trivial-package-local-nicknames#12]
I'd like to use this, but it's under the Unlicense...
Can I have it under an MIT license
or mirrored under an MIT license?
Or BSD0

**Comment by Hexstream** [comment]
Unlicense is strictly better than MIT license, so I'd like to understand your misunderstanding.

**Comment by Slids** [comment]
NVM Google accepts unlicense...
Dealing with Google required bureaucracy...
